name: 'Test Review Bot'

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Build Action
        run: npm run build

      - name: Run PR Reviewer Action
        uses: ./
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.REMOTE_REPOSITORY_PERSIONAL_ACCESS_TOKEN }}
          mode: 'review'
