name: 'Build & Commit on Push Version Branch'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-commit:
    if: "!contains(github.event.head_commit.message, '@build_output_commit')"

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create temporary branch and commit build files
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TEMP_BRANCH="temp-branch-for-build-$TAG_NAME"
          
          # 임시 브랜치 생성 (현재 태그 위치에서)
          git checkout -b $TEMP_BRANCH
          
          # 빌드 파일 커밋
          git add dist/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "feat: Add build files for $TAG_NAME by CI [@build_output_commit]"

      - name: Update tag with build files
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # 기존 태그 삭제
          git push origin :refs/tags/$TAG_NAME

          # 새 태그 푸시
          git tag -a -f $TAG_NAME -m "Release $TAG_NAME with build files"
          git push -f origin $TAG_NAME
          
      - name: Cleanup temporary branch
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          TEMP_BRANCH="temp-build-$TAG_NAME"
          
          # 임시 브랜치 삭제
          git branch -D $TEMP_BRANCH || true
